model_abbreviations = {
    'anthropic/claude-3-5-sonnet-20241022': 'Claude',
    'ai21/jamba-1.5-large': 'Jamba',
    'baichuan': 'Baichuan',
    'deepseek/deepseek-chat': 'DeepSeek',
    'ernie-4.0-turbo-8k-latest': 'Wenxiaoyan',
    'gemini/gemini-pro': 'Gemini',
    'gigachat': 'GigaChat',
    'mistral/mistral-large-latest': 'Mistral',
    'mistral/open-mixtral-8x22b': 'Mixtral',
    'openai/gpt-4o': 'GPT-4o',
    'silma-9b': 'Silma',
    'teuken': 'Teuken',
    'together_ai/meta-llama/meta-llama-3.1-405b-instruct-turbo': 'LLaMA-3.1',
    'together_ai/meta-llama/llama-3.2-90b-vision-instruct-turbo': 'LLaMA-3.2',
    'together_ai/qwen/qwen2.5-72b-instruct-turbo': 'Qwen',
    'vikhr-nemo': 'Vikhr',
    'xai/grok-beta': 'Grok',
    'yandexgpt': 'YandexGPT',
    'jais': 'Jais',
}
model_org = {
    'anthropic/claude-3-5-sonnet-20241022': 'Anthropic',
    'ai21/jamba-1.5-large': 'AI21',
    'baichuan': 'Baichuan',
    'deepseek/deepseek-chat': 'DeepSeek',
    'ernie-4.0-turbo-8k-latest': 'Baidu',
    'gemini/gemini-pro': 'Google',
    'gigachat': 'Sberbank',
    'mistral/mistral-large-latest': 'Mistral',
    'mistral/open-mixtral-8x22b': 'Mistral',
    'openai/gpt-4o': 'OpenAI',
    'silma-9b': 'SILMA AI',
    'teuken': 'OpenGPT-X',
    'together_ai/meta-llama/meta-llama-3.1-405b-instruct-turbo': 'Meta',
    'together_ai/meta-llama/llama-3.2-90b-vision-instruct-turbo': 'Meta',
    'together_ai/qwen/qwen2.5-72b-instruct-turbo': 'Alibaba',
    'vikhr-nemo': 'Vikhr',
    'xai/grok-beta': 'xAI',
    'yandexgpt': 'Yandex',
    'jais': 'G42',
}


# OLD values below
# model_abbreviations = {
#     'openai/gpt-3.5-turbo': 'GPT-3.5',
#     'openai/gpt-4-0125-preview': 'GPT-4',
#     'openai/gpt-4o': 'GPT-4o',
#     'mistral/mistral-large-latest': 'Mistral-Large',
#     'mistral/open-mixtral-8x22b': 'Open-Mixtral',
#     'anthropic/claude-3-haiku-20240307': 'Claude-3h',
#     'anthropic/claude-3-opus-20240229': 'Claude-3o',
#     'together_ai/Qwen/Qwen1.5-14B-Chat': 'Qwen-14B',
#     'together_ai/Qwen/Qwen1.5-72B-Chat': 'Qwen-72B',
#     'deepinfra/meta-llama/Llama-2-70b-chat-hf': 'LLaMA-2',
#     'perplexity/llama-3-sonar-large-32k-chat': 'LLaMA-3',
#     'perplexity/llama-3-sonar-large-32k-online': 'LLaMA-3o',
#     'perplexity/llama-3-70b-instruct': 'LLaMA-3i',
#     'gemini/gemini-pro': 'Gemini-Pro',
#     'ERNIE-Bot': 'ERNIE-Bot',
#     'jais': 'Jais',
#     'jais_no_system_prompt': 'Jais*',
# }
# model_org = {
#     'openai/gpt-3.5-turbo': 'OpenAI',
#     'openai/gpt-4-0125-preview': 'OpenAI',
#     'openai/gpt-4o': 'OpenAI',
#     'mistral/mistral-large-latest': 'Mistral',
#     'mistral/open-mixtral-8x22b': 'Mistral',
#     'anthropic/claude-3-haiku-20240307': 'Anthropic',
#     'anthropic/claude-3-opus-20240229': 'Anthropic',
#     'together_ai/Qwen/Qwen1.5-14B-Chat': 'Alibaba',
#     'together_ai/Qwen/Qwen1.5-72B-Chat': 'Alibaba',
#     'deepinfra/meta-llama/Llama-2-70b-chat-hf': 'Meta',
#     'perplexity/llama-3-sonar-large-32k-chat': 'Meta',
#     'perplexity/llama-3-sonar-large-32k-online': 'Meta',
#     'perplexity/llama-3-70b-instruct': 'Meta',
#     'gemini/gemini-pro': 'Google',
#     'ERNIE-Bot': 'Baidu',
#     'jais': 'G42',
#     'jais_no_system_prompt': 'G42',
# }
# model_org_color = {
#     'OpenAI': '#e41a1c',
#     'Mistral': '#377eb8',
#     'Anthropic': '#4daf4a',
#     'Alibaba': '#984ea3',
#     'Meta': '#ff7f00',
#     'Google': '#f781bf',
#     'Baidu': '#a65628',
#     'G42': '#ffff33'
# }
# language_shape = {
#     'en': 'o',
#     'zh': 'P'
# }